### ISSUE TITLE
will_paginate pagination navigation labels aren't being localised

### ISSUE THREAD

**Issue by crowbot** [mysociety/alaveteli#1163]
See, for example, the pagination links on http://www.infoprovsechny.cz/body/list/all - they say "previous label" "next label" and "page gap"

**Comment by laurentS** [comment]
Quick and dirty fix for this:
create a file called `config/locales/<your_locale>.yml` (we use fr.yml) with this content:
```yaml
fr:   # <--- replace this with your locale and translate as needed below
  will_paginate:
    previous_label: "&#8592; Page précédente"
    next_label: "Page suivante &#8594;"
    page_gap: "&hellip;"

```
and restart nginx or whatever server you're using.
