### ISSUE TITLE
Sass @extends are causing selector bloat

### ISSUE THREAD

**Issue by zarino** [mysociety/alaveteli#3845]
Working on some Alaveteli Pro styles this sprint, I’ve noticed we’ve got some serious selector bloat, especially around buttons and button-like elements. For example, here’s part of the styling for the dropdown "Actions" button on WhatDoTheyKnow:

![screen shot 2017-03-20 at 14 04 44](https://cloud.githubusercontent.com/assets/739624/24103126/301349e8-0d76-11e7-92e3-e337edf974be.png)

```css
a.button-secondary,
.request-header__action-bar a.action-menu__button,
.request-footer__action-bar__actions a.action-menu__button,
.authority__header__action-bar .action-bar__follow-button a.link_button_green,
.authority__header__action-bar .feed_link_sidebar a.link_button_green,
#header_right a[href$="/report/new"],
#right_column a[href$="/report/new"],
div.pagination a,
div.pagination a:visited,
.pagination a.previous_page,
.pagination a.next_page,
.pagination a.current,
.button-secondary,
.request-header__action-bar .action-menu__button,
.request-footer__action-bar__actions .action-menu__button,
.authority__header__action-bar .action-bar__follow-button .link_button_green,
.authority__header__action-bar .feed_link_sidebar .link_button_green,
.authority__header__action-bar .authority__body__sidebar .list-filter-item input[type=submit],
#header_right a[href$="/report/new"],
#right_column a[href$="/report/new"],
div.pagination span.current,
div.pagination a,
div.pagination a:visited,
.pagination .previous_page,
.pagination .next_page,
.pagination .current,
.button-secondary:visited,
.request-header__action-bar .action-menu__button:visited,
.request-footer__action-bar__actions .action-menu__button:visited,
.authority__header__action-bar .action-bar__follow-button .link_button_green:visited,
.authority__header__action-bar .feed_link_sidebar .link_button_green:visited,
.authority__header__action-bar .authority__body__sidebar .list-filter-item input[type=submit]:visited,
#header_right a[href$="/report/new"]:visited,
#right_column a[href$="/report/new"]:visited,
div.pagination a:visited,
.pagination .previous_page:visited,
.pagination .next_page:visited,
.pagination .current:visited {
    background-color: #e2dfd9;
    color: #333333;
    font-weight: normal;
}
```

I expect this is being caused by using `@extend` when we should, instead, be applying two or more classes to an element in a more BEM-like manner.

I expect (hope!) that gzipping stylesheets is mitigating most of the effect this selector bloat is having on our loading times. But it still feels like a bug we should fix, if only to make *our own* Sass compilation times a little faster!
