### ISSUE TITLE
CSS padding bug on header inside correspondence-delivery message

### ISSUE THREAD

**Issue by zarino** [mysociety/alaveteli#4215]
![screen shot 2017-09-11 at 14 44 31](https://user-images.githubusercontent.com/739624/30277494-dc0d585c-96ff-11e7-89cd-bd681ff25252.png)

The existing `.correspondence_delivery h2` ruleset really needs to override the padding that’s being inherited from:

```css
.correspondence h2 {
    padding: 1.2em 1.2em 0;
}
```

(Aside: Why does that `.correspondence h2` padding rule even exist?)
