### ISSUE TITLE
Apply masks to UTF-8 binary data

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#5497]
Here's a failing spec:

```diff
diff --git a/spec/lib/alaveteli_text_masker_spec.rb b/spec/lib/alaveteli_text_masker_spec.rb
index 10beea328..8b2777c14 100644
--- a/spec/lib/alaveteli_text_masker_spec.rb
+++ b/spec/lib/alaveteli_text_masker_spec.rb
@@ -73,6 +73,11 @@ describe AlaveteliTextMasker do
         expect(result).to eq("His email was xxx@xxx.xxx")
       end

+      it 'replaces UTF-8 email addresses' do
+        data = 'héllø@example.org'
+        result = class_instance.apply_masks(data, 'application/vnd.ms-word')
+        expect(result).to eq 'xxxxxxx@xxxxxxx.xxx'
+      end

       it "replaces UCS-2 addresses in Word documents" do
         data = "His email was f\000o\000o\000@\000b\000a\000r\000.\000c\000o\000m\000, indeed"
```
```
Failures:

  1) AlaveteliTextMasker#apply_masks applying masks to binary replaces UTF-8 email addresses
     Failure/Error: expect(result).to eq 'xxxxxxx@xxxxxxx.xxx'

       expected: "xxxxxxx@xxxxxxx.xxx"
            got: "héllø@example.org"

       (compared using ==)
     # ./spec/lib/alaveteli_text_masker_spec.rb:79:in `block (4 levels) in <top (required)>'
```

Spotted while reviewing https://github.com/mysociety/alaveteli/pull/5474.
