### ISSUE TITLE
Transient spec failure in RefusalAdvice.default

### ISSUE THREAD

**Issue by gbp** [mysociety/alaveteli#6006]
Seed 36145

```
Failures:

  1) classifying a request marking request as rejected displays a thank you message post redirect
     Failure/Error: files = Rails.configuration.paths['config/refusal_advice'].existent

     NoMethodError:
       undefined method `existent' for nil:NilClass
     # ./app/models/refusal_advice.rb:6:in `default'
     # ./app/controllers/help_controller.rb:29:in `unhappy'
     # ./app/controllers/application_controller.rb:118:in `record_memory'
     # ./lib/strip_empty_sessions.rb:15:in `call'
     # ./spec/integration/alaveteli_dsl.rb:93:in `classify_request'
     # ./spec/integration/classify_request_spec.rb:176:in `block (4 levels) in <top (required)>'
     # ./spec/integration/classify_request_spec.rb:175:in `block (3 levels) in <top (required)>'
```
