### ISSUE TITLE
Allow customising spam detection with regular expressions

### ISSUE THREAD

**Issue by laurentS** [mysociety/alaveteli#7844]
The default values for `user_spam_scorer` are hardcoded for `DEFAULT_SPAM_NAME_FORMAT` in
https://github.com/mysociety/alaveteli/blob/develop/config/user_spam_scorer.yml-example#L4.

This ticket is to propose a solution to allow site owners to customise this list, including with regexps.

At madada, we use the following patch:
```patch
diff --git a/config/initializers/user_spam_scorer.rb b/config/initializers/user_spam_scorer.rb
index 0c68a6135..ddff950f9 100644
--- a/config/initializers/user_spam_scorer.rb
+++ b/config/initializers/user_spam_scorer.rb
@@ -4,13 +4,11 @@ require 'user_spam_scorer'
 path = Rails.root.join('config/user_spam_scorer.yml')

 if File.exist?(path)
-  settings = YAML.load(File.read(path))['user_spam_scorer']
+  settings = YAML.load(File.read(path), permitted_classes: [Regexp])['user_spam_scorer']
   settings.each do |key, value|
     case key
     when 'ip_ranges'
       value = value.map { |v| IPAddr.new(v) }
-    when /_format/
-      raise "UserSpamScorer: Can't load Regexp from YAML file"
     end

     UserSpamScorer.public_send("#{key}=", value)
```
against `v0.43.1.0`, along with the following custom `config/user_spam_scorer.yml` file:

```yaml
user_spam_scorer:
  currency_symbols:
    - £
  suspicious_domains:
    - mail.ru
  spam_domains:
    - 7x.cz
  suspicious_user_agents:
    - curl
  suspicious_ip_ranges:
    - 127.0.0.0/8
  spam_name_formats:
    - ...
    - !ruby/regexp '/\A.*CRM.*\z/'
    - !ruby/regexp '/.*(http|https):\/\/.*/i'  <-- these are not the default
```

This works well enough, and I think it could be integrated into upstream alaveteli with no disadvantage.
If you feel that this is an acceptable solution, I can open a PR with the corresponding changes.
